services:
    rmq:
        image: rabbitmq:3.7.18-management-alpine
        ports:
            - '5672:5672'
            - '15672:15672'
        healthcheck:
            test: rabbitmq-diagnostics check_port_connectivity
            interval: 1s
            timeout: 3s
            retries: 30
    nest-app-publisher:
        build:
            context: ../publisher
            dockerfile: ../docker/Dockerfile.dev
        ports:
            - '3000:3000'
        depends_on:
            rmq:
                condition: service_healthy
        env_file:
            - ../publisher/.env
        develop:
            watch:
                - action: sync
                  path: ../src
                  target: /app/src
                  ignore:
                      - node_modules/
                - action: rebuild
                  path: ../package.json
    nest-app-consumer:
        build:
            context: ../consumer
            dockerfile: ../docker/Dockerfile.dev
        ports:
            - '3001:3001'
        depends_on:
            rmq:
                condition: service_healthy
        env_file:
            - ../consumer/.env
        develop:
            watch:
                - action: sync
                  path: ../src
                  target: /app/src
                  ignore:
                      - node_modules/
                - action: rebuild
                  path: ../package.json
